stages:
  - test

jobs:
  include:
  - stage: test
    os: linux
    language: generic
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libstdc++6
          - fonts-droid
    before_script:
      - git clone https://github.com/flutter/flutter.git -b beta --depth 1
    script:
      - "./flutter/bin/flutter upgrade"
      - "./flutter/bin/flutter test"
